#pragma once

// Define app constants
#define SOFTWARE_TITLE "Editor"
#define WINDOW_WIDTH   640
#define WINDOW_HEIGHT  480

// States should be +1 on the button's IDs
#define STATE_ENTITY 4
#define STATE_TRIS 3
#define STATE_ADDLINE 2
#define STATE_ADDVERTEX 1 // Drawing vertices
#define STATE_NONE 0      // Idling

// Mapview
#define MAPVIEW_GRID_SIZE_X 16
#define MAPVIEW_GRID_SIZE_Y 16
#define MAPVIEW_LINE_NORMAL_LENGTH 8
#define MAPVIEW_START_X (MAPVIEW_GRID_SIZE_X * 8)
#define MAPVIEW_WIDTH   (WINDOW_WIDTH - MAPVIEW_START_X)
#define MAPVIEW_HEIGHT  (WINDOW_HEIGHT - MAPVIEW_GRID_SIZE_X * 2)

// Toolbox
#define TOOLBOX_BUTTON_MARGIN 8
#define TOOLBOX_BUTTON_ICON_MARGIN 2
#define TOOLBOX_BUTTON_WIDTH  (MAPVIEW_START_X - TOOLBOX_BUTTON_MARGIN*2)
#define TOOLBOX_BUTTON_HEIGHT 20
#define TOOLBOX_BUTTON_STATE_NONE 0
#define TOOLBOX_BUTTON_STATE_ON   1
#define TOOLBOX_BUTTON_AMOUNT     4

// Statusbar
#define STATUSBAR_WIDTH   (MAPVIEW_WIDTH - 1)
#define STATUSBAR_HEIGHT  (WINDOW_HEIGHT - MAPVIEW_HEIGHT)
#define STATUSBAR_START_X (MAPVIEW_START_X + 1)
#define STATUSBAR_START_Y (WINDOW_HEIGHT - STATUSBAR_HEIGHT)

// Utils
#define COORD_ON_MAPVIEW(x, y)   ((x) > MAPVIEW_START_X && (y) < MAPVIEW_HEIGHT)
#define COORD_ON_STATUSBAR(x, y) ((x) > MAPVIEW_START_X && (y) > MAPVIEW_HEIGHT)