#pragma once

#define MAPVIEW_COLOR_BACKGROUND           0x00, 0x00, 0x00
#define MAPVIEW_COLOR_OUTLINE              0xFF, 0xA0, 0x00
#define MAPVIEW_COLOR_GRID                 0x20, 0x20, 0x20
#define MAPVIEW_COLOR_VERTEXSELECTION      0xFF, 0x00, 0x00
#define MAPVIEW_COLOR_VERTEX               0xFF, 0xFF, 0x00
#define MAPVIEW_COLOR_LINE                 0xFF, 0xFF, 0xFF
#define MAPVIEW_COLOR_LINESELECTION        0xFF, 0x00, 0x00
#define MAPVIEW_COLOR_LINENORMAL           0x8F, 0x8F, 0x8F
#define MAPVIEW_COLOR_ENTITYANGLE          0xFF, 0x00, 0xFF

#define TOOLBOX_COLOR_BUTTON_BACKGROUND    0xFF, 0xA0, 0x00
#define TOOLBOX_COLOR_BUTTON_BACKGROUND_ON 0x9F, 0x40, 0x00

#define STATUSBAR_COLOR_BACKGROUND         MAPVIEW_COLOR_BACKGROUND
#define STATUSBAR_COLOR_OUTLINE            MAPVIEW_COLOR_OUTLINE
